#ifndef __HTTP_TYPES_STATUSES__
#define __HTTP_TYPES_STATUSES__ 1

#define HTTP_STATUS_100 100
#define HTTP_STATUS_CONTINUE "Continue"
#define HTTP_STATUS_101 101
#define HTTP_STATUS_SWITCHING_PROTOCOLS "Switching Protocols"
#define HTTP_STATUS_102 102
#define HTTP_STATUS_PROCESSING "Processing"
#define HTTP_STATUS_103 103
#define HTTP_STATUS_EARLY_HINTS "Early Hints"
// #define HTTP_STATUS_104 "104"
// #define HTTP_STATUS_"UPLOAD_RESUMPTION_SUPPORTED_(TEMPORARY___REGISTERED_2024_11_13,_EXPIRES_2025_11_13)" ""Upload Resumption Supported (TEMPORARY - registered 2024-11-13, expires 2025-11-13)""
// #define HTTP_STATUS_105-199 "105-199"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_200 200
#define HTTP_STATUS_OK "OK"
#define HTTP_STATUS_201 201
#define HTTP_STATUS_CREATED "Created"
#define HTTP_STATUS_202 202
#define HTTP_STATUS_ACCEPTED "Accepted"
#define HTTP_STATUS_203 203
#define HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION "Non-Authoritative Information"
#define HTTP_STATUS_204 204
#define HTTP_STATUS_NO_CONTENT "No Content"
#define HTTP_STATUS_205 205
#define HTTP_STATUS_RESET_CONTENT "Reset Content"
#define HTTP_STATUS_206 206
#define HTTP_STATUS_PARTIAL_CONTENT "Partial Content"
#define HTTP_STATUS_207 207
#define HTTP_STATUS_MULTI_STATUS "Multi-Status"
#define HTTP_STATUS_208 208
#define HTTP_STATUS_ALREADY_REPORTED "Already Reported"
// #define HTTP_STATUS_209-225 "209-225"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_226 226
#define HTTP_STATUS_IM_USED "IM Used"
// #define HTTP_STATUS_227-299 "227-299"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_300 300
#define HTTP_STATUS_MULTIPLE_CHOICES "Multiple Choices"
#define HTTP_STATUS_301 301
#define HTTP_STATUS_MOVED_PERMANENTLY "Moved Permanently"
#define HTTP_STATUS_302 302
#define HTTP_STATUS_FOUND "Found"
#define HTTP_STATUS_303 303
#define HTTP_STATUS_SEE_OTHER "See Other"
#define HTTP_STATUS_304 304
#define HTTP_STATUS_NOT_MODIFIED "Not Modified"
#define HTTP_STATUS_305 305
#define HTTP_STATUS_USE_PROXY "Use Proxy"
// #define HTTP_STATUS_306 "306"
// #define HTTP_STATUS_(UNUSED) "(Unused)"
#define HTTP_STATUS_307 307
#define HTTP_STATUS_TEMPORARY_REDIRECT "Temporary Redirect"
#define HTTP_STATUS_308 308
#define HTTP_STATUS_PERMANENT_REDIRECT "Permanent Redirect"
// #define HTTP_STATUS_309-399 "309-399"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_400 400
#define HTTP_STATUS_BAD_REQUEST "Bad Request"
#define HTTP_STATUS_401 401
#define HTTP_STATUS_UNAUTHORIZED "Unauthorized"
#define HTTP_STATUS_402 402
#define HTTP_STATUS_PAYMENT_REQUIRED "Payment Required"
#define HTTP_STATUS_403 403
#define HTTP_STATUS_FORBIDDEN "Forbidden"
#define HTTP_STATUS_404 404
#define HTTP_STATUS_NOT_FOUND "Not Found"
#define HTTP_STATUS_405 405
#define HTTP_STATUS_METHOD_NOT_ALLOWED "Method Not Allowed"
#define HTTP_STATUS_406 406
#define HTTP_STATUS_NOT_ACCEPTABLE "Not Acceptable"
#define HTTP_STATUS_407 407
#define HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED "Proxy Authentication Required"
#define HTTP_STATUS_408 408
#define HTTP_STATUS_REQUEST_TIMEOUT "Request Timeout"
#define HTTP_STATUS_409 409
#define HTTP_STATUS_CONFLICT "Conflict"
#define HTTP_STATUS_410 410
#define HTTP_STATUS_GONE "Gone"
#define HTTP_STATUS_411 411
#define HTTP_STATUS_LENGTH_REQUIRED "Length Required"
#define HTTP_STATUS_412 412
#define HTTP_STATUS_PRECONDITION_FAILED "Precondition Failed"
#define HTTP_STATUS_413 413
#define HTTP_STATUS_CONTENT_TOO_LARGE "Content Too Large"
#define HTTP_STATUS_414 414
#define HTTP_STATUS_URI_TOO_LONG "URI Too Long"
#define HTTP_STATUS_415 415
#define HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE "Unsupported Media Type"
#define HTTP_STATUS_416 416
#define HTTP_STATUS_RANGE_NOT_SATISFIABLE "Range Not Satisfiable"
#define HTTP_STATUS_417 417
#define HTTP_STATUS_EXPECTATION_FAILED "Expectation Failed"
// #define HTTP_STATUS_418 "418"
// #define HTTP_STATUS_(UNUSED) "(Unused)"
// #define HTTP_STATUS_419-420 "419-420"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_421 421
#define HTTP_STATUS_MISDIRECTED_REQUEST "Misdirected Request"
#define HTTP_STATUS_422 422
#define HTTP_STATUS_UNPROCESSABLE_CONTENT "Unprocessable Content"
#define HTTP_STATUS_423 423
#define HTTP_STATUS_LOCKED "Locked"
#define HTTP_STATUS_424 424
#define HTTP_STATUS_FAILED_DEPENDENCY "Failed Dependency"
#define HTTP_STATUS_425 425
#define HTTP_STATUS_TOO_EARLY "Too Early"
#define HTTP_STATUS_426 426
#define HTTP_STATUS_UPGRADE_REQUIRED "Upgrade Required"
// #define HTTP_STATUS_427 "427"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_428 428
#define HTTP_STATUS_PRECONDITION_REQUIRED "Precondition Required"
#define HTTP_STATUS_429 429
#define HTTP_STATUS_TOO_MANY_REQUESTS "Too Many Requests"
// #define HTTP_STATUS_430 "430"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_431 431
#define HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE "Request Header Fields Too Large"
// #define HTTP_STATUS_432-450 "432-450"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_451 451
#define HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS "Unavailable For Legal Reasons"
// #define HTTP_STATUS_452-499 "452-499"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
#define HTTP_STATUS_500 500
#define HTTP_STATUS_INTERNAL_SERVER_ERROR "Internal Server Error"
#define HTTP_STATUS_501 501
#define HTTP_STATUS_NOT_IMPLEMENTED "Not Implemented"
#define HTTP_STATUS_502 502
#define HTTP_STATUS_BAD_GATEWAY "Bad Gateway"
#define HTTP_STATUS_503 503
#define HTTP_STATUS_SERVICE_UNAVAILABLE "Service Unavailable"
#define HTTP_STATUS_504 504
#define HTTP_STATUS_GATEWAY_TIMEOUT "Gateway Timeout"
#define HTTP_STATUS_505 505
#define HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED "HTTP Version Not Supported"
#define HTTP_STATUS_506 506
#define HTTP_STATUS_VARIANT_ALSO_NEGOTIATES "Variant Also Negotiates"
#define HTTP_STATUS_507 507
#define HTTP_STATUS_INSUFFICIENT_STORAGE "Insufficient Storage"
#define HTTP_STATUS_508 508
#define HTTP_STATUS_LOOP_DETECTED "Loop Detected"
// #define HTTP_STATUS_509 "509"
// #define HTTP_STATUS_UNASSIGNED "Unassigned"
// #define HTTP_STATUS_510 "510"
// #define HTTP_STATUS_NOT_EXTENDED_(OBSOLETED) "Not Extended (OBSOLETED)"
#define HTTP_STATUS_511 511
#define HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED "Network Authentication Required"

#endif // __HTTP_TYPES_STATUSES__
